	# --- Configuration Variables ---
CC      = gcc
CFLAGS  =  # Added -Wextra for more warnings, -g for debugging
LDFLAGS = -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
TARGET  = main 
SOURCES = main.c Generics.c

main:
	gcc  main.c Generics.c -Wall -Wextra -g -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o main

